name:                adventofcode
version:             0.1.0.0
github:              "githubuser/adventofcode"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/adventofcode#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers
- parsec
- mtl
- microlens-platform

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

_exe-defs: &exe-defaults
  main:                Main.hs
  ghc-options:
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N
  dependencies:
  - adventofcode

executables:
  day01:
    <<: *exe-defaults
    source-dirs:         day01
  day02:
    <<: *exe-defaults
    source-dirs:         day02
  day03:
    <<: *exe-defaults
    source-dirs:         day03
  day04:
    <<: *exe-defaults
    source-dirs:         day04
  day05:
    <<: *exe-defaults
    source-dirs:         day05
  day06:
    <<: *exe-defaults
    source-dirs:         day06
  day07:
    <<: *exe-defaults
    source-dirs:         day07
  day08:
    <<: *exe-defaults
    source-dirs:         day08
  day09:
    <<: *exe-defaults
    source-dirs:         day09
  day11:
    <<: *exe-defaults
    source-dirs:         day11
  day12:
    <<: *exe-defaults
    source-dirs:         day12
  day13:
    <<: *exe-defaults
    source-dirs:         day13
  day14:
    <<: *exe-defaults
    source-dirs:         day14
  day15:
    <<: *exe-defaults
    source-dirs:         day15
  day18:
    <<: *exe-defaults
    source-dirs:         day18
  day19:
    <<: *exe-defaults
    source-dirs:         day19
  day20:
    <<: *exe-defaults
    source-dirs:         day20
  day21:
    <<: *exe-defaults
    source-dirs:         day21

tests:
  adventofcode-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - adventofcode
